# fly.toml file generated for webstack-go-sqlite on 2022-09-21T22:12:34-04:00

app = "webstack-go-sqlite"

[experimental]
  enable_consul = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
